version: '3'

services:
  mongo:
    build:
      context: .
      dockerfile: Dockerfile-mongo
    ports:
      - "27017:27017"
  redis:
    image: redis
  web:
    build:
      context: .
      dockerfile: Dockerfile-web
    command: bash -c "python manage.py migrate && python manage.py runserver 0.0.0.0:8000"
    ports:
      - "8000:8000"
    depends_on:
      - mongo
      - redis
  cache:
    build:
      context: .
      dockerfile: Dockerfile-cache
    ports:
      - "8080:80"
    depends_on:
      - web
